MODULE REALLOCATE_UTILS
  USE ISO_FORTRAN_ENV, ONLY: DP => REAL64
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: REALLOCATE

  INTERFACE REALLOCATE
    MODULE PROCEDURE REALLOCATE_1D_REAL, REALLOCATE_1D_INT
    MODULE PROCEDURE REALLOCATE_2D_REAL
    MODULE PROCEDURE REALLOCATE_3D_REAL
    MODULE PROCEDURE REALLOCATE_4D_REAL
  END INTERFACE

CONTAINS

SUBROUTINE REALLOCATE_1D_REAL(A, N)
  REAL(DP), ALLOCATABLE, INTENT(INOUT) :: A(:)
  INTEGER, INTENT(IN) :: N
  IF (.NOT. ALLOCATED(A)) THEN
    ALLOCATE(A(N), SOURCE=0.0_DP)
  ELSE IF (SIZE(A) /= N) THEN
    DEALLOCATE(A)
    ALLOCATE(A(N), SOURCE=0.0_DP)
  END IF
  A = 0.0_DP
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_INT(A, N)
  INTEGER, ALLOCATABLE, INTENT(INOUT) :: A(:)
  INTEGER, INTENT(IN) :: N
  IF (.NOT. ALLOCATED(A)) THEN
    ALLOCATE(A(N), SOURCE=0)
  ELSE IF (SIZE(A) /= N) THEN
    DEALLOCATE(A)
    ALLOCATE(A(N), SOURCE=0)
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_REAL(A, N1, N2)
  REAL(DP), ALLOCATABLE, INTENT(INOUT) :: A(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  IF (.NOT. ALLOCATED(A)) THEN
    ALLOCATE(A(N1, N2), SOURCE=0.0_DP)
  ELSE IF (ANY(SHAPE(A) /= [N1, N2])) THEN
    DEALLOCATE(A)
    ALLOCATE(A(N1, N2), SOURCE=0.0_DP)
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_3D_REAL(A, N1, N2, N3)
  REAL(DP), ALLOCATABLE, INTENT(INOUT) :: A(:,:,:)
  INTEGER, INTENT(IN) :: N1, N2, N3
  IF (.NOT. ALLOCATED(A)) THEN
    ALLOCATE(A(N1, N2, N3), SOURCE=0.0_DP)
  ELSE IF (ANY(SHAPE(A) /= [N1, N2, N3])) THEN
    DEALLOCATE(A)
    ALLOCATE(A(N1, N2, N3), SOURCE=0.0_DP)
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_4D_REAL(A, N1, N2, N3, N4)
  REAL(DP), ALLOCATABLE, INTENT(INOUT) :: A(:,:,:,:)
  INTEGER, INTENT(IN) :: N1, N2, N3, N4
  IF (.NOT. ALLOCATED(A)) THEN
    ALLOCATE(A(N1, N2, N3, N4), SOURCE=0.0_DP)
  ELSE IF (ANY(SHAPE(A) /= [N1, N2, N3, N4])) THEN
    DEALLOCATE(A)
    ALLOCATE(A(N1, N2, N3, N4), SOURCE=0.0_DP)
  END IF
END SUBROUTINE

END MODULE REALLOCATE_UTILS
